[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
[CONFIGURATIONS]
"A2UI001L" 
"AZ1G202G" 
[CURRENT_CONFIGURATION]
"AZ1G202G" 
[CURRENT_SESSION]
"DefaultSession" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_A2UI001L]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_A2UI001L]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_AZ1G202G]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_AZ1G202G]
"DefaultSession" 
[GENERAL_DATA_CONFIGURATION_SESSION_AZ1G202G_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_A2UI001L_DefaultSession]
[GENERAL_DATA_SESSION_DefaultSession]
[END]
